spring.application.name=api-gateway
server.port=8765

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

spring.security.user.name=admin
spring.security.user.password=admin123

eureka.client.healthcheck.enabled=false